
spring:
  flyway:
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false # delaying connection acquisition turn of auto commit mode
      connection-timeout: 30000
      idleTimeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true # delaying hibernates connection acquisition ,turn of auto commit mode

        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com:
      zaxxer:
        hikari: TRACE # turn on hikari connection pool logging ,each 30s logs the status of the connection pool in the console
    org:
      springframework:
        orm:
          jpa: debug #logging transaction details
        transaction: debug #logging transaction details
      hibernate:
         orm:
          jdbc:
            bind : trace # to display hibernate 6 binding parameters

