apiVersion: v1
kind: PersistentVolume
metadata:
  name: notes-db-pv
  namespace: app-notes-dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
