apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-ui-deployment
  namespace: app-notes-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-ui-app
  template:
    metadata:
      labels:
        app: notes-ui-app
    spec:
      containers:
        - name: notes-ui-container
          image: e2rabi11/notes-ui:1.0.0-SNAPSHOT
          containerPort: 8080