apiVersion: v1
kind: Service
metadata:
  labels:
    app: notes-ui-svc
  name: notes-ui-service
  namespace: app-notes-dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: notes-ui-app