apiVersion: v1
kind: Service
metadata:
  labels:
    app: notes-db-svc
  name: notes-db-service
  namespace: app-notes-dev
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: notes-db-app